# Generated by Django 3.1.3 on 2020-11-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('language', models.TextField()),
                ('english_version', models.TextField()),
                ('translated_version', models.TextField()),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
