# Generated by Django 3.1.3 on 2020-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_add_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='category',
            new_name='word_category',
        ),
        migrations.AddField(
            model_name='category',
            name='related_words',
            field=models.ManyToManyField(to='vocabulary.Words'),
        ),
    ]
