# Generated by Django 3.2.5 on 2021-08-01 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_model_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name_plural': 'Words'},
        ),
        migrations.RenameField(
            model_name='words',
            old_name='word_category',
            new_name='word_categories',
        ),
        migrations.AlterField(
            model_name='words',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocabulary.languages'),
        ),
    ]
