# Generated by Django 3.2.5 on 2021-08-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_add_languages_model_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='languages',
            table='languages',
        ),
    ]
